inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

Bundler/DuplicatedGem:
  Enabled: false

Lint/HandleExceptions:
  Exclude:
    - Rakefile

Layout/IndentHeredoc:
  Enabled: false

Style/NumericPredicate:
  Exclude:
    - lib/netsnmp.rb

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false