sudo: required
services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y sed
  - sudo apt-get install -y snmp
  - sudo apt-get install -y libsnmp-dev
  - sudo apt-get install -y snmpd
  - wget http://archive.ubuntu.com/ubuntu/pool/multiverse/s/snmp-mibs-downloader/snmp-mibs-downloader_1.1.dsc
  - wget http://archive.ubuntu.com/ubuntu/pool/multiverse/s/snmp-mibs-downloader/snmp-mibs-downloader_1.1.tar.gz
  - sudo dpkg-source -x snmp-mibs-downloader_1.1.dsc
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine

before_script:
  - sudo download-mibs 
  - sudo sed -i 's/^mibs/#mibs/g' /etc/snmp/snmp.conf
  - spec/support/start_docker.sh
after_script: spec/support/stop_docker.sh

install:
  - bundle install --path .bundle

script:
  - bundle exec rake

language: ruby
rvm:
  - 2.0
#  - 2.1
#  - 2.2
#  - 2.3
#  - ruby-head
#  - jruby
#  - rbx-3
