sudo: required
services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y snmp
  - sudo apt-get install -y libsnmp-dev
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine

before_script: 
  - spec/support/start_docker.sh
after_script: spec/support/stop_docker.sh

install:
  - bundle install --path .bundle

script:
  - bundle exec rake

language: ruby
rvm:
  - 2.0
#  - 2.1
#  - 2.2
#  - 2.3
#  - ruby-head
#  - jruby
#  - rbx-3
