sudo: required
services:
  - docker

install:
  - gem i rubygems-update -v '<3' && update_rubygems
  - bundle install --path .bundle

script:
  - spec/support/specs.sh run

language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
  - jruby-head
  - truffleruby
matrix:
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head
    # to figure out later
  - rvm: truffleruby
