# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Coverage

on:
  workflow_run:
    workflows: ["Tests"]
    # branches: []
    types: 
      - completed

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: coverage-report
      - uses: actions/setup-ruby@v2
        with:
          ruby-version: '2.7'
      - run: gem install --no-cov simplecov
      - run: rake coverage:report
      - uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage/
